import Header from "@/components/layout/Header";
import TopBar from "@/components/layout/TopBar";
import Footer from "@/components/layout/Footer";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms and Conditions | ExaltRide",
  description: "Terms and Conditions for ExaltRide - Your car accessories destination",
};

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Header />
      <div className="hidden md:block">
        <TopBar />
      </div>

      <main className="flex-1 container mx-auto px-4 py-8 max-w-4xl">
        <div className="bg-white rounded-xl shadow-sm p-6 md:p-10">
          <div className="flex items-center gap-4 mb-6">
            <div className="bg-[#001F5F] p-3 rounded-xl">
              <FileText className="h-8 w-8 text-yellow-400" />
            </div>
            <div>
              <h1 className="text-2xl md:text-3xl font-bold text-[#001F5F]">
                Terms and Conditions
              </h1>
              <p className="text-gray-500 text-sm">ExaltRide Terms of Use</p>
            </div>
          </div>

          <p className="text-xs text-gray-500 italic mb-8">
            Disclaimer: In case of any discrepancy or difference, the English version will take precedence over the translation
          </p>

          <div className="prose prose-sm md:prose max-w-none text-gray-700">
            <p className="mb-4">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>

            <p className="mb-6">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform" (exaltride.com))
            </p>

            <div className="bg-gray-50 p-4 rounded-lg mb-6">
              <p className="mb-0">
                The Platform is owned by <strong>Torqis Horizons Private Limited</strong>, a company incorporated under the Companies Act, 1956 with its registered office at IX-210, Tagore Gali, Gandhi Nagar, East Delhi, New Delhi - 110031, India (hereinafter referred to as "Torqis").
              </p>
            </div>

            <p className="mb-6">
              Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with Torqis Horizons Private Limited and these terms and conditions including the policies constitute Your binding obligations, with ExaltRide.
            </p>

            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
              <p className="text-yellow-800 font-medium mb-0">
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
              </p>
            </div>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Membership Eligibility</h2>
            <p className="mb-4">
              Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform.
            </p>
            <p className="mb-6">
              If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/permission of a parent or legal guardian.
            </p>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Your Account and Registration Obligations</h2>
            <p className="mb-4">
              If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password.
            </p>
            <p className="mb-6">
              You agree that if You provide any information that is untrue, inaccurate, not current or incomplete, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform.
            </p>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Communications</h2>
            <p className="mb-6">
              When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required.
            </p>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Platform for Transaction and Communication</h2>
            <p className="mb-4">
              The Platform enables the Buyer and Seller to transact on the Platform. Torqis is not and cannot be a party to or control in any manner any transaction between the Platform's Users.
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone.</li>
              <li>Torqis does not make any representation or Warranty as to specifics of the products or services proposed to be sold or offered.</li>
              <li>Torqis is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers.</li>
              <li>At no time shall Torqis hold any right, title or interest over the products.</li>
            </ul>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Charges</h2>
            <p className="mb-4">
              Torqis may charge a nominal fee for browsing and buying on the Platform. Torqis reserves the right to change its Fee Policy from time to time.
            </p>
            <p className="mb-6">
              <strong>What is the platform fee?</strong> Fee levied by Torqis to sustain the efficient operations and continuous improvement of the platform, for a hassle-free app experience.
            </p>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Use of the Platform</h2>
            <p className="mb-4">You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>
            <p className="mb-4">You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>Belongs to another person and to which You do not have any right</li>
              <li>Is grossly harmful, harassing, blasphemous, defamatory, obscene, or otherwise unlawful</li>
              <li>Is misleading in any way</li>
              <li>Infringes upon or violates any third party's rights</li>
              <li>Contains software viruses or any other computer code designed to interrupt or destroy functionality</li>
              <li>Threatens the unity, integrity, defence, security or sovereignty of India</li>
            </ul>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">Grievance Officer</h2>
            <p className="mb-4">
              In accordance with Information Technology Act 2000 and rules made there under and the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are provided below:
            </p>
            <div className="bg-gray-50 p-4 rounded-lg mb-6">
              <p className="font-semibold">Mr. Harsh Surana</p>
              <p>COO/Grievance Officer</p>
              <p>Torqis Horizons Pvt Ltd</p>
              <p>IX-210, Tagore Gali, Gandhi Nagar,</p>
              <p>East Delhi, New Delhi - 110031, India</p>
              <p className="mt-2">
                Email: <a href="mailto:grievance@exaltride.com" className="text-blue-600 hover:underline">grievance@exaltride.com</a>
              </p>
              <p>Time: Mon - Sat (9:00 - 18:00)</p>
            </div>

            <h2 className="text-xl font-bold text-[#001F5F] mt-8 mb-4">How You Can Contact Us</h2>
            <p className="mb-4">
              If your query or concern is regarding your orders, to get instant help with your orders, follow these simple steps:
            </p>
            <ol className="list-decimal pl-6 space-y-2 mb-6">
              <li>Visit <a href="https://www.exaltride.com/helpcentre" className="text-blue-600 hover:underline">https://www.exaltride.com/helpcentre</a></li>
              <li>Select your order and tap 'Help'</li>
              <li>Choose 'Chat with us'</li>
            </ol>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
